### ISSUE TITLE
Additional key bindings for text input

### ISSUE THREAD

**Issue by modk** [hwipl/nuqql#1]
Additional shell-like key bindings for text input would be nice:

- ctrl-e - go to end of line
- ctrl-a - go to beginning of line
- ctrl-u - delete line
- ctrl-k - delete from cursor to end of line

**Comment by hwipl** [comment]
I added those keybinds to the devel branch. Please test, if it works for you.

**Comment by modk** [comment]
Works for me, thanks!

**Comment by hwipl** [comment]
OK, thanks. Fix is in devel and will be in next release. Closing issue for now.
