### ISSUE TITLE
Zoom on last url in history

### ISSUE THREAD

**Issue by modk** [hwipl/nuqql#13]
It would be very useful to have the zoom focus on the last url in the history or maybe on the last url in the currently visible part of the history.

**Comment by hwipl** [comment]
Together with the history searching support, I added support for this to the devel branch. From an Input Window, you can now jump into the zoomed history and search for the string "http" with the F10 key. It uses the regular searching code, so you can go to the next/previous match with the "n" and "p" keys. Please test, if that works for you.

**Comment by modk** [comment]
That's a nice feature, F10 works for me. Just have to avoid too many non-http URLs.
