### ISSUE TITLE
Fuzzy switching between conversations

### ISSUE THREAD

**Issue by modk** [hwipl/nuqql#14]
It would be nice to have a global shortcut that allows switching between conversations in a fuzzy-search manner.
A shortcut to switch to the next unread message/conversation would also be helpful.

**Comment by hwipl** [comment]
The latest devel branch contains a couple of additions:

Now, there are "go to next/previous conversation" keybindings. You can
* switch to the next unread conversation or a more recently used conversation with the `CTRL-N`
* go back to a previously used conversation with `CTRL-B`

Also, there is a conversation list filtering mode. You can
* switch into filter mode with the `/` (only when browsing the conversation list) and with `CTRL-V` keys
* enter a filter string that is matched by checking if all characters appear in the given order in the conversation status or conversation name
* browse matches with `UP` and `DOWN` keys

Please check, if that works for you.

**Comment by modk** [comment]
Works nicely, thanks.
