### ISSUE TITLE
Add F9 for message zooming.

### ISSUE THREAD

**Issue by modk** [hwipl/nuqql#3]
In centerim, F9 (or F10?) zooms into a single message in order to allow copy and paste. It would be nice to have this as well.

**Comment by hwipl** [comment]
I checked in centerim and it is F9. I pushed some updates to the devel branch that allow zooming the whole message history window when you are in it with the F9 key. Please check, if that is OK for you or if you would still prefer single message zooming.

**Comment by modk** [comment]
Zooming itself works now, but would it be possible to remove the border in order to be able to mark e.g. URLs?

**Comment by hwipl** [comment]
I removed the border in the devel branch. Please check, if that works for you.

**Comment by modk** [comment]
I am able to copy and paste URLs with this solution.

**Comment by hwipl** [comment]
OK, thanks. This will be in the next release. Closing issue for now.
