### ISSUE TITLE
[Long-term] Make colors adjustable or use system/terminal colors

### ISSUE THREAD

**Issue by modk** [hwipl/nuqql#4]
It would be nice to use the default 16/256 terminal colors. Full customization is probably not necessary.

**Comment by hwipl** [comment]
The latest devel branch supports a color config in ~/.config/nuqql/colors.ini. It is automatically created/loaded when you start nuqql and contains all supported color and text attribute settings with their (default) values. Currently supported values are:
* colors: default, black, blue, cyan, green, magenta, red, white, yellow
* attributes: normal, bold

Please check if that works for you.

**Comment by modk** [comment]
Works for me now with the latest change that allows color8-color15. Thanks.
