### ISSUE TITLE
Away status

### ISSUE THREAD

**Issue by modk** [hwipl/nuqql#5]
Add different status and, most importantly, "away". Aren't centerim users always "away"?

**Comment by hwipl** [comment]
You are right, they are always "away" ;)

I updated the existing backends as well as nuqql (devel branch) and introduced an account status message. With the updates you can, e.g., go into the slixmppd conversation and send the following commands:

* ``account <id> status get`` 
* ``account <id> status set <status>``

to get and set the current status of the account identified by ``<id>``. For example, slixmppd allows setting the status  to 'available', 'dnd', 'chat', 'xa', and 'away'.

**Comment by modk** [comment]
Setting the status works for me now. I'm thinking wether it would be useful to have a persistent away status that gets restored on startup but probably not.

**Comment by hwipl** [comment]
I added a persistent global status to the devel branch. With this change, you can set a global status that is set on all backends and accounts. You can get and set the global status in the {nuqql} conversation with:
* ``global-status get``
* ``global-status set <status>``

Please check, if that is sufficient ;)

**Comment by modk** [comment]
Appears to be working for me, thanks.
