### ISSUE TITLE
History searching

### ISSUE THREAD

**Issue by modk** [hwipl/nuqql#8]
centerim allows history search by pressing '/' in history mode. This would be useful for nuqql as well.

**Comment by hwipl** [comment]
I added initial history searching support to the devel branch. You can now search the history (when browsing it) by pressing "/". It opens up a new Input Window for the search text. You can go the the next match with the "n" key and to the previous match with the "p" key. Please test if that works for you.

**Comment by modk** [comment]
Works now, thanks.
